User.create(username: 'Candice', password: 'password1')
User.create(username: 'Imogen', password: 'password1')
User.create(username: 'Zelda', password: 'password1')
User.create(username: 'Dashy Boy', password: 'password1')
User.create(username: 'Diogi', password: 'password1')
User.create(username: 'Gaia Cat', password: 'password1')